language: go

go:
    - "1.11"

before_install:
    - pwd
    - go get -d github.com/ibmdb/go_ibm_db
    - pwd
    - ls
    - cd $GOPATH/gopath/github.com
    - ls
    - pwd
script:
    - go run testing.go