language: go

go:
    - "1.12"
    
os:
  - osx

before_install:
    - go get -d github.com/ibmdb/go_ibm_db
    - cd $GOPATH/src/github.com/ibmdb/go_ibm_db/installer
    - go run setup.go
    - export DB2HOME=$GOPATH/src/github.com/ibmdb/go_ibm_db/installer/clidriver
    - export CGO_CFLAGS=-I$DB2HOME/include
    - export CGO_LDFLAGS=-L$DB2HOME/lib
    - export DYLD_LIBRARY_PATH=$GOPATH/src/github.com/ibmdb/go_ibm_db/installer/clidriver/lib
    - cd $GOPATH/src/github.com/akhilravuri1/TravisTest
 script:
    - go run testing.go