language: go

go:
    - "1.11"

before_install:
    - go get -d github.com/ibmdb/go_ibm_db
    - cd $GOPATH/src/github.com/ibmdb/go_ibm_db/installer
    - go run setup.go
    - ls
    - cd clidriver
    - ls
script:
    - go run testing.go