language: go

go:
    - "1.11"

before_script:
    - go get -d github.com/ibmdb/go_ibm_db
    - cd $GOAPTH/src/github.com/ibmdb/go_ibm_db/installer
    - go run setup.go
    
script:
    - go run testing.go